#!/usr/bin/env bash
# Print Path B (preferred for ALIGNED) + Path A/C + live probe/audit.
# Scientific effect: NONE. Read-only against d6g8k5htny-coder/main.
#
# Reads portable/patches/BASE_TIP.txt for Path C currency (no hardcoded SHA).
# Post-#41: default main ALIGNED landing ≠ hardening Path-C tree.
set -euo pipefail

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
cd "$ROOT"

BASE_TIP_FILE="$ROOT/portable/patches/BASE_TIP.txt"
BASE_TIP_LINE="(missing BASE_TIP.txt)"
BASE_TIP_SHORT="unknown"
if [[ -f "$BASE_TIP_FILE" ]]; then
  BASE_TIP_LINE="$(tr -d '\r' <"$BASE_TIP_FILE" | head -n1)"
  BASE_TIP_SHORT="${BASE_TIP_LINE##* }"
  BASE_TIP_SHORT="${BASE_TIP_SHORT:0:7}"
fi

# Batch 257: header used to freeze Batch 169 / tip 1c6e74b / "write DENIED" while
# portable/PATH_C_STATUS.json already reported WRITABLE @ fa32d11. Prefer live status
# (never print tokens / raw device secrets beyond existing GH_DEVICE_LOGIN paths).
STATUS_FILE="$ROOT/portable/PATH_C_STATUS.json"
WRITE_STATE="UNKNOWN"
STATUS_TIP="$BASE_TIP_SHORT"
IDLE_STATUS=""
STATUS_GEN=""
if [[ -f "$STATUS_FILE" ]]; then
  eval "$(python3 -c '
import json,shlex,sys
from pathlib import Path
p=Path(sys.argv[1])
try:
    d=json.loads(p.read_text(encoding="utf-8"))
except Exception:
    d={}
def emit(k,v):
    if v is None:
        v=""
    print(f"{k}={shlex.quote(str(v))}")
emit("WRITE_STATE", d.get("write_state") or "UNKNOWN")
emit("STATUS_TIP", (d.get("tip") or d.get("base_tip") or "")[:7])
emit("IDLE_STATUS", d.get("idle_status") or "")
emit("STATUS_GEN", d.get("generated_at") or "")
' "$STATUS_FILE")"
fi
[[ -n "$STATUS_TIP" ]] || STATUS_TIP="$BASE_TIP_SHORT"

echo "=== Batch 518 — PERMANENT window; Path C BASE_TIP ${BASE_TIP_SHORT}; write ${WRITE_STATE}; tip ${STATUS_TIP}${IDLE_STATUS:+; idle ${IDLE_STATUS}}; unrestricted/auto-approve; HOLD VOID ==="
echo " Batch 518: tip_or_eng TIP_DRIFT keep-prior living script_stale + unfreeze 517→518 @2f7a5a9 (LIVE cd66a65)"
echo " Batch 517: tip_or_eng TIP_DRIFT keep-prior living script_stale + unfreeze 516→517 @2f7a5a9 (LIVE cd66a65)"
echo " Batch 516: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 515/514/513/512/511; covers research496/499/501/503/509/514 gap"
echo " Batch 516: tip_or_eng TIP_DRIFT keep-prior + unfreeze 515→516 @2f7a5a9 (LIVE cd66a65)"
echo " Batch 515: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 514/513/512/511/510; covers research496/499/501/503/509/514 gap"
echo " Batch 515: tip_sync_watch tip_moved keep-prior + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 515: tip_or_eng TIP_DRIFT keep-prior + unfreeze 514→515 @2f7a5a9 (LIVE cd66a65)"
echo " Batch 513: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 512/511/510/508/507; covers research496/499/501/503/509 gap"
echo " Batch 513: tip_sync_watch tip_moved keep-prior + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 514: tip_or_eng living script_stale republish + unfreeze 513→514 @2f7a5a9"
echo " Batch 514: tip_sync_watch tip_moved keep-prior + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 513: tip_or_eng idle_no_commit hunt-negative + unfreeze 512→513 @2f7a5a9"
echo " Batch 512: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 511/510/508/507/506; covers research496/499/501/503/509 gap"
echo " Batch 512: tip_sync_watch tip_moved keep-prior + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 512: tip_or_eng idle_no_commit hunt-negative + unfreeze 511→512 @2f7a5a9"
echo " Batch 511: tip_sync_watch living script_stale republish + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 511: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 510/508/507/506/505; covers research496/499/501/503/509 gap"
echo " Batch 511: tip_or_eng idle_no_commit hunt-negative + unfreeze 510→511 @2f7a5a9"
echo " Batch 510: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 508/507/506/505/504; covers research496/499/501/503/509 gap"
echo " Batch 510: tip_or_eng idle_no_commit hunt-negative + unfreeze 509→510 @2f7a5a9"
echo " Batch 510: tip_sync_watch living script_stale republish + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 508: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 507/506/505/504/502; covers research496/499/501/503 gap"
echo " Batch 509: tip_or_eng living tgz_newer republish + unfreeze 508→509 @2f7a5a9"
echo " Batch 508: tip_sync_watch living script_stale republish + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 508: tip_or_eng idle_no_commit hunt-negative + unfreeze 507→508 @2f7a5a9"
echo " Batch 507: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 506/505/504/502/500; covers research496/499/501/503 gap"
echo " Batch 507: tip_sync_watch living script_stale republish + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 507: tip_or_eng idle_no_commit hunt-negative + unfreeze 506→507 @2f7a5a9"
echo " Batch 506: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 505/504/502/500/498; covers research496/499/501/503 gap"
echo " Batch 506: tip_sync_watch living script_stale republish + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 506: tip_or_eng idle_no_commit hunt-negative + unfreeze 505→506 @2f7a5a9"
echo " Batch 505: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 504/502/500/498/497; covers research496/499/501/503 gap"
echo " Batch 505: tip_sync_watch living script_stale republish + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 505: tip_or_eng living tgz_newer republish + unfreeze 504→505 @2f7a5a9"
echo " Batch 504: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 502/500/498/497/495; covers research496/499/501/503 gap"
echo " Batch 504: tip_sync_watch living script_stale republish + Soft Intent single-header preserve @2f7a5a9"
echo " Batch 502: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 500/498/497/495/494; covers research496/499/501 gap"
echo " Batch 502: tip_sync_watch living script_stale republish + Soft Intent single-header restore @2f7a5a9"
echo " Batch 504: tip_or_eng idle_no_commit hunt-negative + unfreeze 503→504 @2f7a5a9"
echo " Batch 500: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 500: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 498/497/495/494/493; covers research496/499 gap"
echo " Batch 499: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 501: tip_or_eng idle_no_commit hunt-negative + unfreeze 500→501 @2f7a5a9"
echo " Batch 498: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 497/495/494/493/492; covers research496 gap"
echo " Batch 497: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 496: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 495: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 494: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 497: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 495/494/493/492/491; covers research496 gap"
echo " Batch 499: tip_or_eng idle_no_commit hunt-negative + unfreeze 498→499 @2f7a5a9"
echo " Batch 496: tip_or_eng idle_no_commit hunt-negative + unfreeze 495→496 @2f7a5a9"
echo " Batch 495: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 494/493/492/491/490"
echo " Batch 495: tip_or_eng idle_no_commit hunt-negative + unfreeze 494→495 @2f7a5a9"
echo " Batch 494: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 493/492/491/490/489"
echo " Batch 494: tip_or_eng idle_no_commit hunt-negative + unfreeze 493→494 @2f7a5a9"
echo " Batch 493: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 492: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 493: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 492/491/490/489/488"
echo " Batch 493: tip_or_eng living script_stale republish + unfreeze 492→493 @2f7a5a9"
echo " Batch 492: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 491/490/489/488/487"
echo " Batch 492: tip_or_eng idle_no_commit hunt-negative + unfreeze 491→492 @2f7a5a9"
echo " Batch 491: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 491: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 490/489/488/487/485"
echo " Batch 491: tip_or_eng living script_stale republish + unfreeze 490→491 @2f7a5a9"
echo " Batch 490: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 489/488/487/485/484"
echo " Batch 490: tip_or_eng idle_no_commit hunt-negative + unfreeze 489→490 @2f7a5a9"
echo " Batch 489: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 489: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 488/487/485/484/482"
echo " Batch 489: tip_or_eng idle_no_commit hunt-negative + unfreeze 488→489 @2f7a5a9"
echo " Batch 488: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 488: tip_or_eng living tgz_newer republish + unfreeze 487→488 @2f7a5a9"
echo " Batch 488: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 487/485/484/482/481"
echo " Batch 487: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 487: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 485/484/482/481/480"
echo " Batch 485: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 484/482/481/480/478"
echo " Batch 487: tip_or_eng living script_stale republish + unfreeze 486→487 @2f7a5a9"
echo " Batch 486: tip_or_eng idle_no_commit hunt-negative + unfreeze 485→486 @2f7a5a9"
echo " Batch 485: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 485: tip_or_eng idle_no_commit hunt-negative + unfreeze 484→485 @2f7a5a9"
echo " Batch 484: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 484: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 482/481/480/478/477"
echo " Batch 484: tip_or_eng living script_stale republish + unfreeze 483→484 @2f7a5a9"
echo " Batch 483: tip_or_eng idle_no_commit hunt-negative + unfreeze 482→483 @2f7a5a9"
echo " Batch 482: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 482: tip_or_eng living script_stale republish + unfreeze 481→482 @2f7a5a9"
echo " Batch 482: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 481/480/478/477/476"
echo " Batch 481: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 481: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 480/478/477/476/475"
echo " Batch 481: tip_or_eng idle_no_commit hunt-negative + unfreeze 480→481 @2f7a5a9"
echo " Batch 480: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 480: tip_or_eng living script_stale republish + unfreeze 479→480 @2f7a5a9"
echo " Batch 480: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 478/477/476/475/474"
echo " Batch 479: tip_or_eng idle_no_commit hunt-negative + unfreeze 478→479 @2f7a5a9"
echo " Batch 478: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 478: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 477/476/475/474/473"
echo " Batch 478: tip_or_eng idle_no_commit hunt-negative + unfreeze 477→478 @2f7a5a9"
echo " Batch 477: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 477: tip_or_eng idle_no_commit hunt-negative + unfreeze 476→477 @2f7a5a9"
echo " Batch 477: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 476/475/474/473/472"
echo " Batch 476: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 476: tip_or_eng idle_no_commit hunt-negative + unfreeze 475→476 @2f7a5a9"
echo " Batch 476: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 475/474/473/472/471"
echo " Batch 475: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 475: tip_or_eng idle_no_commit hunt-negative + unfreeze 474→475 @2f7a5a9"
echo " Batch 475: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 474/473/472/471/470"
echo " Batch 474: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 474: tip_or_eng idle_no_commit hunt-negative + unfreeze 473→474 @2f7a5a9"
echo " Batch 474: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 473/472/471/470/469"
echo " Batch 473: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 473: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 472/471/470/469/468"
echo " Batch 473: tip_or_eng living tgz_newer republish + unfreeze 472→473 @2f7a5a9"
echo " Batch 471: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 472: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 472: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 471/470/469/468/467"
echo " Batch 472: tip_or_eng idle_no_commit hunt-negative + unfreeze 471→472 @2f7a5a9"
echo " Batch 471: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 470/469/468/467/466"
echo " Batch 470: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 470: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 469/468/467/466/465"
echo " Batch 471: tip_or_eng living script_stale republish + unfreeze 470→471 @2f7a5a9"
echo " Batch 470: tip_or_eng idle_no_commit hunt-negative + unfreeze 469→470 @2f7a5a9"
echo " Batch 469: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 468/467/466/465/464"
echo " Batch 469: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 468: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 467/466/465/464/463"
echo " Batch 469: tip_or_eng idle_no_commit hunt-negative + unfreeze 468→469 @2f7a5a9"
echo " Batch 467: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 467: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 466/465/464/463/462"
echo " Batch 468: tip_or_eng idle_no_commit hunt-negative + unfreeze 467→468 @2f7a5a9"
echo " Batch 467: tip_or_eng idle_no_commit hunt-negative + unfreeze 466→467 @2f7a5a9"
echo " Batch 466: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 465/464/463/462/461; covers research465 gap"
echo " Batch 465: research_stack_audit_watch_no_promotion gap-fill — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 464/463/462/461/460"
echo " Batch 466: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 465: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 466: tip_or_eng living script_stale republish + unfreeze 465→466 @2f7a5a9"
echo " Batch 465: tip_or_eng idle_no_commit hunt-negative + unfreeze 464→465 @2f7a5a9"
echo " Batch 464: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 463/462/461/460/459"
echo " Batch 464: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 463: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 462/461/460/459/458"
echo " Batch 464: tip_or_eng idle_no_commit hunt-negative + unfreeze 463→464 @2f7a5a9"
echo " Batch 463: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 463: tip_or_eng idle_no_commit hunt-negative + unfreeze 462→463 @2f7a5a9"
echo " Batch 462: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 462: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 461/460/459/458/457"
echo " Batch 462: tip_or_eng idle_no_commit hunt-negative + unfreeze 461→462 @2f7a5a9"
echo " Batch 461: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 460/459/458/457/456"
echo " Batch 461: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 461: tip_or_eng idle_no_commit hunt-negative + unfreeze 460→461 @2f7a5a9"
echo " Batch 460: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 459/458/457/456/455"
echo " Batch 460: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 460: tip_or_eng idle_no_commit hunt-negative + unfreeze 459→460 @2f7a5a9"
echo " Batch 459: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 459: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 458/457/456/455/454"
echo " Batch 459: tip_or_eng living tgz_newer republish + unfreeze 458→459 @2f7a5a9"
echo " Batch 458: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 458: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 457/456/455/454/451"
echo " Batch 458: tip_or_eng idle_no_commit hunt-negative + unfreeze 457→458 @2f7a5a9"
echo " Batch 457: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 456/455/454/451/450"
echo " Batch 457: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 457: tip_or_eng idle_no_commit hunt-negative + unfreeze 456→457 @2f7a5a9"
echo " Batch 456: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 455/454/451/450/449"
echo " Batch 456: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 456: tip_or_eng living script_stale republish + unfreeze 455→456 @2f7a5a9"
echo " Batch 455: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 454/451/450/449/448"
echo " Batch 455: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 455: tip_or_eng living script_stale republish + unfreeze 454→455 @2f7a5a9"
echo " Batch 454: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 451/450/449/448/447"
echo " Batch 454: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 454: tip_or_eng living script_stale republish + unfreeze 453→454 @2f7a5a9"
echo " Batch 453: tip_or_eng idle_no_commit hunt-negative + unfreeze 451→453 @2f7a5a9"
echo " Batch 452: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 451: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 450/449/448/447/446"
echo " Batch 451: tip_or_eng idle_no_commit hunt-negative + unfreeze 450→451 @2f7a5a9"
echo " Batch 451: tip_sync_watch living tgz_newer republish + parent-pin inv @2f7a5a9"
echo " Batch 450: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 449/448/447/446/445"
echo " Batch 450: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 450: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 449: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 448/447/446/445/444"
echo " Batch 449: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 449: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 448: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 447/446/445/444/443"
echo " Batch 448: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 448: CI Intent soften Batch441/445 tip_sync living_brief asserts @2f7a5a9"
echo " Batch 448: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 447: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 446/445/444/443/441"
echo " Batch 447: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 447: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 446: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 446: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 445/444/443/441/440"
echo " Batch 446: tip_or_eng living script_stale republish + unfreeze 445→446 @2f7a5a9"
echo " Batch 445: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 444/443/441/440"
echo " Batch 445: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 444: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 443/441/440/438"
echo " Batch 444: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 445: tip_or_eng living script_stale republish + unfreeze 444→445 @2f7a5a9"
echo " Batch 443: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 441/440/438/437"
echo " Batch 444: tip_or_eng living script_stale republish + unfreeze 443→444 @2f7a5a9"
echo " Batch 443: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 441: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 440/438/437/436"
echo " Batch 443: tip_or_eng living script_stale republish + unfreeze 442→443 @2f7a5a9"
echo " Batch 441: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 442: tip_or_eng living tgz_newer republish + unfreeze 441→442 @2f7a5a9"
echo " Batch 440: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 438/437/436/435"
echo " Batch 440: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 441: tip_or_eng living script_stale republish + unfreeze 440→441 @2f7a5a9"
echo " Batch 438: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 437/436/435/434"
echo " Batch 438: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 440: tip_or_eng living script_stale republish + unfreeze 439→440 @2f7a5a9"
echo " Batch 439: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 437: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 437: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 436/435/434/433"
echo " Batch 438: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 436: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 435/434/433/431"
echo " Batch 436: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 437: tip_or_eng living script_stale republish + unfreeze 436→437 @2f7a5a9"
echo " Batch 435: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 434/433/431/430"
echo " Batch 436: tip_or_eng living script_stale republish + unfreeze 435→436 @2f7a5a9"
echo " Batch 434: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 435: tip_or_eng living script_stale republish + unfreeze 434→435 @2f7a5a9"
echo " Batch 434: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 433/431/430/428"
echo " Batch 433: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 433: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 431/430/428/427"
echo " Batch 434: tip_or_eng living script_stale republish + unfreeze 433→434 @2f7a5a9"
echo " Batch 430: tip_sync_watch living script_stale republish + parent-pin inv @2f7a5a9"
echo " Batch 433: tip_or_eng living script_stale republish + unfreeze 432→433 @2f7a5a9"
echo " Batch 431: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 430/428/427/426"
echo " Batch 432: tip_or_eng living script_stale republish + unfreeze 431→432 @2f7a5a9"
echo " Batch 430: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 428/427/426/424"
echo " Batch 431: tip_or_eng living script_stale republish + unfreeze 430→431 @2f7a5a9"
echo " Batch 427: tip_sync_watch living tgz_newer republish + parent-pin inv @2f7a5a9"
echo " Batch 430: tip_or_eng living script_stale republish + unfreeze 429→430 @2f7a5a9"
echo " Batch 428: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 427/426/424/422"
echo " Batch 429: tip_or_eng living script_stale republish + unfreeze 428→429 @2f7a5a9"
echo " Batch 427: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 426/424/422/420"
echo " Batch 428: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 427: tip_or_eng living script_stale republish + unfreeze 426→427 @2f7a5a9"
echo " Batch 426: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 424/422/420/418"
echo " Batch 426: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 426: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 425: tip_sync_watch living tgz_newer republish + parent-pin inv @2f7a5a9"
echo " Batch 425: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 424: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 422/420/418/416"
echo " Batch 424: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 424: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 422: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 420/418/416/414"
echo " Batch 422: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 423: tip_or_eng living tgz_newer republish + unfreeze 422→423 @2f7a5a9"
echo " Batch 422: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 420: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 418/416/414/412"
echo " Batch 421: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 420: tip_sync_watch living tgz_newer republish + parent-pin inv @2f7a5a9"
echo " Batch 420: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 418: tip_sync_watch living tgz_newer republish + parent-pin inv @2f7a5a9"
echo " Batch 418: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 416/414/412"
echo " Batch 419: tip_or_eng living tgz_newer republish + unfreeze 418→419 @2f7a5a9"
echo " Batch 418: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 416: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 417: tip_or_eng living script_stale republish + unfreeze 416→417 @2f7a5a9"
echo " Batch 416: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 414/412/410/405"
echo " Batch 416: tip_or_eng living script_stale republish + unfreeze 415→416 @2f7a5a9"
echo " Batch 414: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 412/410/405"
echo " Batch 414: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 415: tip_or_eng living tgz_newer republish + unfreeze 414→415 @2f7a5a9"
echo " Batch 414: tip_or_eng living tgz_newer republish + unfreeze 413→414 @2f7a5a9"
echo " Batch 412: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 410/408/405"
echo " Batch 412: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 413: tip_or_eng living tgz_newer republish + unfreeze 412→413 @2f7a5a9"
echo " Batch 412: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 410: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 408/405"
echo " Batch 411: tip_or_eng living tgz_newer republish + unfreeze 410→411 @2f7a5a9"
echo " Batch 410: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 410: post tip_sync living inv parent-pin @2f7a5a9"
echo " Batch 410: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 409: post tip_sync living inv parent-pin @2f7a5a9"
echo " Batch 408: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 409: tip_or_eng living tgz_newer republish + unfreeze 408→409 @2f7a5a9"
echo " Batch 408: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 405"
echo " Batch 408: tip_or_eng living script_stale republish + inv parent-pin @2f7a5a9"
echo " Batch 408: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 407: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 407: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 406: tip_or_eng living tgz missing/republish + unfreeze 405→406 @2f7a5a9"
echo " Batch 405: research_stack_audit_watch no-promotion @2f7a5a9"
echo " Batch 404: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 404: tip_or_eng living tgz_newer republish + unfreeze 403→404 @2f7a5a9"
echo " Batch 403: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 402: tip_or_eng living tgz_newer republish + unfreeze 401→402 @2f7a5a9"
echo " Batch 401: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 401: tip_or_eng living tgz_newer republish + unfreeze 400→401 @2f7a5a9"
echo " Batch 401: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @2f7a5a9; no delta vs 399"
echo " Batch 400: tip_or_eng inv tip re-pin + living tgz + unfreeze 399→400 @2f7a5a9"
echo " Batch 399: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 399: tip_or_eng idle_no_commit hunt-negative @2f7a5a9"
echo " Batch 399: research_stack_audit_watch no-promotion @2f7a5a9 (13/1/3; delta=0 vs 396)"
echo " Batch 396: tip_or_eng idle_no_commit continue hunt-negative @2f7a5a9"
echo " Batch 398: tip_or_eng living script_stale republish + unfreeze 396→398 @2f7a5a9"
echo " Batch 396: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 396: research_stack_audit_watch no-promotion @2f7a5a9 (13/1/3; delta=0 vs 393)"
echo " Batch 395: tip_or_eng living script_stale republish @2f7a5a9"
echo " Batch 395: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 395: idle tip-stable + unfreeze 394→395 @2f7a5a9"
echo " Batch 394: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 394: tip_or_eng idle after post-idle hunt-negative @2f7a5a9"
echo " Batch 394: post-idle inv tip pin + living + unfreeze 393→394 @2f7a5a9"
echo " Batch 393: tip_or_eng idle tip-stable hunt-negative @2f7a5a9"
echo " Batch 393: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 393: research_stack_audit_watch no-promotion @2f7a5a9 (13/1/3; delta=0 vs 388)"
echo " Batch 392: tip_or_eng unfreeze 391→392 + living script_stale @2f7a5a9"
echo " Batch 390: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 391: post-idle inv tip pin + living + unfreeze 390→391 @2f7a5a9"
echo " Batch 389: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 390: tip_or_eng soften Intent inv tip_sha eq-freeze + living + unfreeze 389→390 @2f7a5a9"
echo " Batch 389: tip_or_eng idle tip-stable + unfreeze 388→389 @2f7a5a9"
echo " Batch 388: research_stack_audit_watch no-promotion @2f7a5a9 (13/1/3; delta=0 vs 387)"
echo " Batch 388: tip_or_eng soften Intent STATUS_GUARD tip_sha pin + living script_stale + unfreeze 387→388 @2f7a5a9"
echo " Batch 387: tip_sync_watch idle_no_commit + parent-pin inv @2f7a5a9"
echo " Batch 387: tip-sync 7caac25→2f7a5a9 keep-prior (SIDE24 theorem-chain sources)"
echo " Batch 387: STATUS_GUARD tip refresh + unfreeze 386→387 @2f7a5a9"
echo " Batch 387: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @7caac25; no delta vs 385"
echo " Batch 386: tip_or_eng soften Intent BASE_TIP pin + living tgz + unfreeze 385→386 @7caac25"
echo " Batch 385: tip_sync_watch idle_no_commit + parent-pin inv @7caac25"
echo " Batch 385: tip-sync ebedb780→7caac25 keep-prior after main #118"
echo " Batch 385: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @7caac25; no delta vs 383/380"
echo " Batch 385: STATUS_GUARD tip refresh + unfreeze 384→385 @7caac25"
echo " Batch 384: tip_or_eng idle tip-stable @ebedb780 + living script_stale republish"
echo " Batch 384: unfreeze last-resort 383→384 + VERIFY refresh_batch 383→384 @ebedb780"
echo " Batch 383: tip_sync_watch idle_no_commit + parent-pin inv @ebedb780"
echo " Batch 383: research_stack_audit_watch no-promotion @ebedb780 (13/1/3; delta=0 vs 380)"
echo " Batch 383: living tgz content-delta + unfreeze 382→383 @ebedb780"
echo " Batch 382: inv tip re-pin after peer living + unfreeze 381→382 @ebedb780"
echo " Batch 381: post-research inv tip pin + living script_stale @ebedb780"
echo " Batch 381: unfreeze last-resort 380→381 + VERIFY refresh_batch 380→381 @ebedb780"
echo " Batch 380: tip_sync_watch idle_no_commit + parent-pin inv @ebedb780"
echo " Batch 380: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @ebedb78; no delta vs 379"
echo " Batch 380: tip_or_eng living script_stale republish after Batch381 peer @ebedb780"
echo " Batch 380: tip_or_eng idle tip-stable @ebedb780 + living tgz content-delta republish"
echo " Batch 380: unfreeze last-resort 379→380 + VERIFY refresh_batch 379→380 @ebedb780"
echo " Batch 379: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @ebedb78; no delta vs 378"
echo " Batch 379: tip_sync_watch idle_no_commit + parent-pin inv + unfreeze 378→379 @ebedb780"
echo " Batch 379: tip_or_eng idle tip-stable @ebedb780 + living script_stale republish"
echo " Batch 379: unfreeze last-resort 378→379 + VERIFY refresh_batch 378→379 @ebedb780"
echo " Batch 378: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @ebedb78; no delta vs 377"
echo " Batch 378: follow-up STATUS_GUARD tip living @ebedb780; living need_upload=0; parent-pin inv"
echo " Batch 378: tip-sync keep-prior 1ae02b9→ebedb78 after main #98 @ebedb78"
echo " Batch 378: tip_or_eng idle tip-stable @1ae02b9"
echo " Batch 378: unfreeze last-resort 377→378 + VERIFY refresh_batch 377→378 @1ae02b9"
echo " Batch 377: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @1ae02b9; no delta vs 376"
echo " Batch 377: tip_sync_watch idle_no_commit + parent-pin inv @1ae02b9"
echo " Batch 377: tip_or_eng idle tip-stable @1ae02b9 (timer watch)"
echo " Batch 377: unfreeze last-resort 376→377 + VERIFY refresh_batch 376→377 @1ae02b9"
echo " Batch 376: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @1ae02b9; no delta vs 375"
echo " Batch 376: tip_sync_watch idle_no_commit + parent-pin inv @1ae02b9"
echo " Batch 376: tip_or_eng idle tip-stable @1ae02b9 + living tgz content-delta republish"
echo " Batch 376: unfreeze last-resort 375→376 + VERIFY refresh_batch 375→376 @1ae02b9"
echo " Batch 375: tip_sync_watch idle_no_commit + parent-pin inv @1ae02b9"
echo " Batch 375: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @1ae02b9; no delta vs 374"
echo " Batch 375: tip_or_eng idle tip-stable @1ae02b9 + living tgz content-delta republish"
echo " Batch 375: unfreeze last-resort 374→375 + VERIFY refresh_batch 374→375 @1ae02b9"
echo " Batch 374: tip_sync_watch idle_no_commit + parent-pin inv @1ae02b9"
echo " Batch 374: research_stack_audit_watch no-promotion @1ae02b9 (13/1/3 open; delta=0 vs 372)"
echo " Batch 374: unfreeze last-resort 373→374 + VERIFY refresh_batch 373→374 @1ae02b9"
echo " Batch 373: tip_or_eng living script_stale republish after inv-tip-pin/unfreeze @1ae02b9"
echo " Batch 373: inv tip re-pin beyond parent after tip_sync idle + unfreeze 372→373 @1ae02b9"
echo " Batch 372: inv tip re-pin beyond parent after research/tip-eng @1ae02b9"
echo " Batch 372: tip_or_eng wake last-resort 370→372 vs print_owner @1ae02b9"
echo " Batch 372: research_stack_audit_watch no-promotion @1ae02b9 (13/1/3 open; delta=0 vs 369)"
echo " Batch 372: unfreeze last-resort 371→372 + VERIFY refresh_batch 371→372 @1ae02b9"
echo " Batch 372: tip_sync_watch idle_no_commit @1ae02b9 (tip_match; living tip/script current; inv parent-pin preserved)"
echo " Batch 371: inv tip re-pin beyond parent after CI Intent soften @1ae02b9"
echo " Batch 371: tip_or_eng CI Intent STATUS_GUARD baseline living soften @1ae02b9"
echo " Batch 371: inv tip re-pin beyond parent after eng-hunt idle @1ae02b9"
echo " Batch 371: idle_no_commit tip-stable watch @1ae02b9 (tip_match; living tip/script current; woke peers)"
echo " Batch 371: unfreeze last-resort 370→371 + VERIFY refresh_batch 370→371 @1ae02b9"
echo " Batch 371: eng_defect_hunt idle_no_commit @1ae02b9 (tip_match; lag=1 skip; living tip/script current)"
echo " Batch 370: eng repair Batch369 tip_eng JSON + wake last-resort 369→370 @1ae02b9"
echo " Batch 370: inv tip re-pin beyond parent after eng-hunt JSON repair @1ae02b9"
echo " Batch 370: tip_or_eng inv tip re-pin beyond parent + living republish @1ae02b9"
echo " Batch 369: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @1ae02b9; no delta vs 367"
echo " Batch 369: tip_or_eng inv tip re-pin beyond parent after living republish @1ae02b9"
echo " Batch 369: tip_or_eng wake last-resort 368→369 + inv tip pin + living republish @1ae02b9"
echo " Batch 369: living script_stale republish after unfreeze idle @1ae02b9"
echo " Batch 369: idle_no_commit tip-stable watch @1ae02b9 (tip_match; living tip/script current; woke peers)"
echo " Batch 369: unfreeze last-resort 368→369 + VERIFY refresh_batch 368→369 @1ae02b9"
echo " Batch 368: living upload confirm + Intent 276/279 --force soften + inv tip pin @1ae02b9"
echo " Batch 368: living script_stale republish after STATUS_GUARD tip refresh @1ae02b9"
echo " Batch 368: tip_sync_watch confirm @1ae02b9 + soften Intent live tip pin (was e3cd7d4)"
echo " Batch 368: tip-sync e3cd7d4→1ae02b9 after main #115 (keep-prior; inventable not promoted)"
echo " Batch 368: STATUS_GUARD tip refresh e3cd7d4→1ae02b9 after tip-sync (guard pass; no promotion)"
echo " Batch 368: tip_or_eng inv tip re-pin beyond parent + last-resort 367→368 + VERIFY 367→368 @e3cd7d4"
echo " Batch 368: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; living tip/script current; inv parent-pinned)"
echo " Batch 367: tip_or_eng inv tip re-pin beyond parent + last-resort 366→367 + VERIFY 366→367 @e3cd7d4"
echo " Batch 367: tip_sync_watch idle_no_commit @e3cd7d4 (tip_match; living tip/script current)"
echo " Batch 367: research_stack_audit_watch no-promotion @e3cd7d4 (13/1/3 open; delta=0 vs 365)"
echo " Batch 367: inv tip re-pin beyond parent after research audit @e3cd7d4"
echo " Batch 366: tip_or_eng inv tip re-pin beyond parent + last-resort 365→366 + VERIFY 365→366 @e3cd7d4"
echo " Batch 366: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; living tip/script current; inv parent-pinned)"
echo " Batch 365: eng unfreeze last-resort 364→365 + VERIFY refresh_batch 364→365 @e3cd7d4"
echo " Batch 365: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @e3cd7d4; no delta vs 362"
echo " Batch 365: living script_stale republish VERIFY refresh_batch 363→364 @e3cd7d4 (tip_match; inv parent-pinned)"
echo " Batch 365: inv tip re-pin beyond parent after living republish @e3cd7d4"
echo " Batch 365: post-research inv tip re-pin beyond parent @e3cd7d4"
echo " Batch 364: tip_or_eng inv tip re-pin beyond parent + last-resort 363→364 + living republish @e3cd7d4"
echo " Batch 364: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; living tip/script current; inv parent-pinned)"
echo " Batch 363: CI Intent living >=N soften + VERIFY refresh_batch 363 + inv tip pin @e3cd7d4"
echo " Batch 363: tip_or_eng inv tip sync after post-eng land + living script_stale republish @e3cd7d4"
echo " Batch 363: tip_or_eng post-living inv tip re-pin beyond parent + last-resort 362→363 @e3cd7d4"
echo " Batch 363: living script_stale republish VERIFY refresh_batch 345→362 @e3cd7d4 (tip_match; inv parent-pinned)"
echo " Batch 362: tip_or_eng post-soften inv tip re-pin + living script_stale republish @e3cd7d4"
echo " Batch 362: tip_or_eng inv tip re-pin beyond parent + last-resort 361→362 + living republish @e3cd7d4"
echo " Batch 362: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @e3cd7d4; no delta vs 361"
echo " Batch 362: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; living tip/script current; paper-trail tgz)"
echo " Batch 361: tip_or_eng inv tip re-pin (beyond parent) + last-resort 360→361 + living republish @e3cd7d4"
echo " Batch 361: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @e3cd7d4; no delta vs 359"
echo " Batch 361: tip_sync_watch idle_no_commit @e3cd7d4 (tip_match; living tip/script current)"
echo " Batch 360: tip_or_eng inv tip re-pin + last-resort 359→360 + living republish @e3cd7d4"
echo " Batch 359: eng repair BATCH345 tip-sync JSON + soften Batch 230 goal_complete living pin"
echo " Batch 359: tip_or_eng post-eng inv tip re-pin + living republish @e3cd7d4"
echo " Batch 360: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; living tip/script current; paper-trail tgz)"
echo " Batch 359: eng living script_stale republish after WAKE359 (batch241; script_stale 1→0)"
echo " Batch 359: soften Batch 357 tip_or_eng Intent action allowlist (ci_audit_watch)"
echo " Batch 359: MULTI_AGENT wake+assign stopped agents @e3cd7d4 (WAKE359; Dylan message-stopped-agents)"
echo " Batch 359: eng living script_stale republish after tip_or_eng tip-pin (batch241; script_stale 1→0)"
echo " Batch 359: tip_or_eng inv tip re-pin after grant/sync lands @e3cd7d4"
echo " Batch 359: grant_check_dual_vector_8of8 tip refresh @e3cd7d4 (BATCH359_GRANT; preserve_durable)"
echo " Batch 359: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @e3cd7d4; no delta vs 357"
echo " Batch 359: tip_sync_watch idle_no_commit @e3cd7d4 (tip_match; living tip/script current)"
echo " Batch 359: inventory_preserve_durable_tip_pin @e3cd7d4 (trial→HEAD; never demote 8/8 on writable=0 DENIED)"

echo " Batch 358: eng living script_stale republish after tip_sync idle (batch241; script_stale 1→0; Intent allowlist living)"
echo " Batch 358: tip_or_eng inv tip re-pin after lands @e3cd7d4"
echo " Batch 358: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; living tip/script current; paper-trail tgz)"
echo " Batch 357: tip_or_eng inv tip re-pin after Batch 356/357 lands @e3cd7d4"
echo " Batch 357: research_stack_audit_watch — open stack 13/1/3; STATUS_GUARD living @e3cd7d4; no promotion"

echo " Batch 357: unfreeze inventory/wake/REFRESH last-resort 356→357 (coordinator wake; tip stable @e3cd7d4)"
echo " Batch 357: tip_sync_watch idle_no_commit @e3cd7d4 (tip_match; living tip/script current; no tip-pin treadmill)"
echo " Batch 357: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @e3cd7d4"
echo " Batch 356: tip_or_eng conflict-marker cleanup + inv tip re-pin @e3cd7d4"
echo " Batch 356: tip_or_eng inv tip re-pin after Intent-fix land @e3cd7d4"
echo " Batch 356: soften INV tip-pin Intent merge dedupe (duplicate def + frozen defect_id)"
echo " Batch 356: inventory_preserve_durable_tip_pin @e3cd7d4 (trial→HEAD; never demote 8/8 on writable=0 DENIED)"
echo " Batch 356: idle_no_commit tip-stable align watch @e3cd7d4 (post-path-c-align-watch; living tip/script current)"
echo " Batch 355: ci_audit_watch idle — CI green @e3cd7d4 (unfreeze living ≥352 incl 355)"
echo " Batch 355: eng living script_stale republish after wake+assign (batch241; script_stale 1→0)"
echo " Batch 355: research_stack_audit_watch_no_promotion — open stack 13/1/3; STATUS_GUARD living @e3cd7d4"
echo " Batch 355: eng living script_stale republish after Batch 355 lands (batch241; script_stale 1→0)"
echo " Batch 355: MULTI_AGENT wake+assign stopped agents @e3cd7d4 (WAKE355; Dylan message-stopped-agents)"

echo " Batch 355: soften INV tip-pin Intent live BASE_TIP pin (e3cd7d4→_living_tip)"
echo " Batch 355: grant_check_dual_vector_8of8 tip refresh @e3cd7d4 (BATCH355_GRANT; preserve_durable)"
echo " Batch 355: MULTI_AGENT wake+assign stopped agents @e3cd7d4 (WAKE355; Dylan message-stopped-agents)"
echo " Batch 355: tip_sync_watch idle_no_commit @e3cd7d4 (tip_match; living tip/script current; no tip-pin treadmill)"
echo " Batch 355: inventory_preserve_durable_tip_pin @e3cd7d4 (trial→HEAD; never demote 8/8 on writable=0 DENIED)"
echo " Batch 354: soften INV tip-pin Intent live BASE_TIP pin (e3cd7d4→_living_tip)"
echo " Batch 354: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; living tip/script current; paper-trail tgz)"

echo " Batch 354: eng living script_stale republish after inv tip-pin (batch241; script_stale 1→0)"
echo " Batch 354: inventory_preserve_durable_tip_pin @e3cd7d4 (trial→HEAD; never demote 8/8 on writable=0 DENIED)"
echo " Batch 353: inventory tip re-pin→HEAD after eng living republish (preserve_durable)"
echo " Batch 353: eng living script_stale republish after research-audit merge (batch241; script_stale 1→0)"
echo " Batch 353: research_stack_audit_watch — open stack 13/1/3; STATUS_GUARD living @e3cd7d4; no promotion"
echo " Batch 353: inventory tip re-pin→HEAD after living republish (preserve_durable)"
echo " Batch 353: living script_stale republish + inventory tip pin→HEAD @e3cd7d4"
echo " Batch 353: wake Path C peers (tip watch, eng hunt, inventory, research audit)"
echo " Batch 353: tip_sync_watch idle @e3cd7d4 (tip_match; living tip/script current; paper-trail tgz)"
echo " Batch 353: inventory_preserve_durable_tip_pin @e3cd7d4 (trial→HEAD; never demote 8/8 on writable=0 DENIED)"
echo " Batch 352: ci_audit_watch idle — CI green @e3cd7d4 (INV_TIP soften + EARLY_FALLBACK isolate)"
echo " Batch 352: tip_or_eng inv tip re-pin + living script_stale republish @e3cd7d4"
echo " Batch 352: inventory_preserve_durable_tip_pin re-pin @e3cd7d4 (trial→HEAD; never demote 8/8 on writable=0)"
echo " Batch 352: MULTI_AGENT wake+assign stopped agents @e3cd7d4 (WAKE352; Dylan message-stopped-agents)"
echo " Batch 352: grant_check_dual_vector_8of8 tip refresh @e3cd7d4 (BATCH352_GRANT; preserve_durable)"
echo " Batch 352: living script_stale republish after inv tip-pin (batch241; script_stale 1→0)"
echo " Batch 352: unfreeze inventory/wake/REFRESH last-resort 351→352 (coordinator wake; tip stable @e3cd7d4)"

echo " Batch 352: tip_sync_watch idle @e3cd7d4 (tip_match; living tip/script current; paper-trail tgz)"
echo " Batch 352: inventory_preserve_durable_tip_pin @e3cd7d4 (trial→HEAD; never demote 8/8 on writable=0 DENIED)"
echo " Batch 351: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; NOT 077464e; living tip/script current; paper-trail tgz)"
echo " Batch 351: research_stack_audit_watch — STATUS_GUARD living @e3cd7d4; eng living script_stale republish"
echo " Batch 351: inventory_preserve_durable_tip_pin @e3cd7d4 (trial→HEAD; never demote 8/8 on writable=0 DENIED)"
echo " Batch 350: soften INV_TIP_PIN Intent action allowlist (peer re-pin rename)"
echo " Batch 351: inventory tip pin after Batch 350 idle (preserve_durable; batch322-soon timer)"
echo " Batch 350: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; living tip/script current; paper-trail tgz)"
echo " Batch 350: inventory tip pin after Batch 349 lands (preserve_durable; trial→HEAD)"
echo " Batch 349: eng_defect_hunt idle_no_commit @e3cd7d4 (tip_match; no concrete eng; lemma_closed=false)"
echo " Batch 349: CI Intent EARLY_FALLBACK isolate in rate-limit unit tests + soften GRANT345 action pin"
echo " Batch 349: inventory tip pin after Batch 348 lands (preserve_durable)"
echo " Batch 348: research_stack_audit_watch — STATUS_GUARD no lag @e3cd7d4; eng living script_stale republish + inv tip pin"
echo " Batch 348: idle_no_commit tip-stable watch @e3cd7d4 (tip_match; living tip/script current; paper-trail tgz)"
echo " Batch 348: inventory tip pin after Batch 347 lands (preserve_durable; trial→HEAD f00459d)"
echo " Batch 348: research stack audit WITHOUT promotion @e3cd7d4 (open_premises=13; lemma_closed=false)"
echo " Batch 347: soften Batch 346 wake Intent live tip pin (e3cd7d4); tip stable @e3cd7d4"
echo " Batch 347: tip_sync_watch idle @e3cd7d4 (tip_match; living tip/script current; paper-trail tgz)"
echo " Batch 347: inventory tip pin after Batch 346 lands (preserve_durable; trial→HEAD a136c2d)"
echo " Batch 346: living script_stale republish after tip-stable @e3cd7d4 (batch241; script_stale 1→0)"
echo " Batch 346: ci_audit_watch idle — early-fallback intact @e3cd7d4; no new CI eng class"
echo " Batch 346: inventory_preserve_durable_tip_pin @e3cd7d4 (trial→HEAD; ultimate fallback 346; never demote 8/8 on writable=0 DENIED)"
echo " Batch 346: STATUS_GUARD tip refresh fcad723→e3cd7d4 after tip-sync (guard pass; no promotion)"
echo " Batch 346: grant_check_dual_vector_8of8 tip refresh @e3cd7d4 (BATCH346_GRANT; preserve_durable)"
echo " Batch 346: MULTI_AGENT wake+assign stopped agents @e3cd7d4 (WAKE346; Dylan message-stopped-agents)"
echo " Batch 346: wake/inventory ultimate fallback return \"346\" (was frozen 345 after WAKE346)"
echo " Batch 346: soften Batch 345 tip_sync_watch Intent live BASE_TIP pin (e3cd7d4); tip stable @e3cd7d4"
echo " Batch 345: tip-sync fcad723→e3cd7d4 after main #105 CONTRIBUTION_PLAN retire (keep-prior; NOT promoted); REFRESH default 345"
echo " Batch 345: tip-sync fcad723→e3cd7d4 (keep-prior; inventable NOT promoted)"
echo " Batch 345: inventory tip pin after tip-sync e3cd7d4 (preserve_durable; trial→HEAD)"
echo " Batch 345: inventory ultimate fallback return \"345\" (was 343 after tip-sync REFRESH 345)"
echo " Batch 343: audit Intent timeout early-fallback (rate-limit reset sleep→raw; CI 36176016910)"
echo " Batch 345: wake ultimate fallback return \"345\" (was frozen 341); single living print_owner header (was dual 344+345)"
echo " Batch 345: MULTI_AGENT wake+assign stopped agents (WAKE345; batch329 timer)"
echo " Batch 343: audit Intent timeout early-fallback (rate-limit reset sleep→raw; CI 36176016910)"
echo " Batch 344: soften Batch 343 tip_sync_watch Intent live BASE_TIP pin (fcad723); tip stable @fcad723"
echo " Batch 344: tip_sync_watch idle @fcad723 (tip_match; living tip/script current; paper-trail tgz)"
echo " Batch 343: STATUS_GUARD tip refresh f244312→fcad723 after tip-sync (guard pass; no promotion)"
echo " Batch 344: idle_no_commit tip-stable watch @fcad723 (batch327 timer pulse)"
echo " Batch 343: inventory ultimate fallback return \"343\" (was frozen 340 after tip-sync REFRESH 343); soften Batch 340 Intent hard pin"
echo " Batch 343: grant inventory tip refresh batch 343 (preserve durable 8/8 on writable=0)"
echo " Batch 343: living script_stale republish after tip-stable watch @f244312"
echo " Batch 343: MULTI_AGENT wake+assign stopped agents (WAKE343)"
echo " Batch 343: WAKE343/340 living tip pins refreshed f244312→fcad723 (wake_tip_at_assign preserved)"
echo " Batch 342: inventory tip refresh batch 342 + soften wake-token Intent live tip pin"
echo " Batch 341: soften Batch 340 Intent living INV_BATCH hard pin after Batch 342 tip-refresh (CI red == \"340\" vs living 342)"
echo " Batch 341: grant inventory tip refresh @f244312 (BATCH341_GRANT; preserve_durable)"
echo "Owner: NO restrictions; agents decide. HOLD on PR #2 is VOID."
echo "Dylan: 48h extended permanently until he intervenes — no 48h finale."
echo "Live PATH_C_STATUS: write_state=${WRITE_STATE} tip=${STATUS_TIP} base_tip=${BASE_TIP_SHORT}${STATUS_GEN:+ generated_at=${STATUS_GEN}} (see portable/PATH_C_STATUS.json; never print tokens)"
echo "Window: $ROOT/scripts/check_autonomous_window.py  # PERMANENT_UNTIL_OWNER_INTERVENES"
echo "Path C ONE-SHOT (Batch 165+): $ROOT/scripts/owner_path_c_oneshot.sh --dry-run"
echo "  token → owner_open_path_c_pr.sh (else owner_land_path_c.sh); no token → unblock menu"
echo "  live: $ROOT/scripts/owner_path_c_oneshot.sh"
echo "  from-bundle: $ROOT/scripts/owner_path_c_oneshot.sh --from-bundle  # prefers .bundle fetch+merge"
echo "  release: batch241-path-c-bundle (prior batch239-path-c-bundle / batch236-path-c-bundle) (.bundle + .patch + oneshot+refresh+PATH_C_STATUS+watch/readme link-only; PATH_C_RELEASE_TAG override ok; prior batch223-path-c-bundle / batch218-path-c-bundle / batch199-path-c-bundle / batch180-path-c-bundle / batch179-path-c-bundle / batch169-path-c-bundle / batch168-path-c-bundle)"
echo "Tip refresh helper (Batch 173/176): $ROOT/scripts/refresh_path_c_bundle.sh  # tip fetch → BASE_TIP → apply_all → .patch+.bundle → VERIFY.json"
echo "  dry-run: $ROOT/scripts/refresh_path_c_bundle.sh --dry-run  # exit 0 tip-stable / 1 TIP_DRIFT (+ fix-path); CI tip-drift dry-sim"
echo "  force rebuild: $ROOT/scripts/refresh_path_c_bundle.sh --force"
echo "Ready assert: $ROOT/scripts/assert_path_c_ready.sh"
echo "Watch (embeds window+route): $ROOT/scripts/watch_main_alignment.py"
echo "ALIGNED drift watch: $ROOT/scripts/aligned_drift_watch.py  # exit 0/1/2; snapshot; --restore-if-writable"
echo "Background lander: $ROOT/scripts/when_writable_land.py  # poll 300s; Path C when writable+ALIGNED; Path B if MISALIGNED"
echo "  tmux: when-writable-land  |  status: /cursor/stores/self/when_writable_land.status.json"
echo "  once sidecar (Batch 267/270; when daemon lock held or lockfile pid= live): /cursor/stores/self/when_writable_land.once.status.json"
echo "  daemon lock: /cursor/stores/self/when_writable_land.status.json.daemon.lock  # second loop → exit 2 (flock or pid-liveness)"
echo "  log: /tmp/cursor/when_writable_land.log  |  STOP: /cursor/stores/self/when_writable_land.stop"
echo "  token: env MAIN_PUSH_TOKEN | /cursor/stores/self/MAIN_PUSH_TOKEN | /workspace/.secrets/MAIN_PUSH_TOKEN | /tmp/gh-dylan-auth/access_token"
echo "  set trial secret (Batch 160): $ROOT/scripts/owner_set_main_push_token.sh --dry-run"
echo "    then: MAIN_PUSH_TOKEN=… $ROOT/scripts/owner_set_main_push_token.sh --dispatch  # gh secret set + land-path-c dry_run=false"
echo "    or: $ROOT/scripts/owner_set_main_push_token.sh --from-gh --dispatch  # uses gh auth token (never printed)"
echo "  once dry: python3 scripts/when_writable_land.py --once --dry-run"
echo "Device login (Dylan): $ROOT/portable/GH_DEVICE_LOGIN.md  # https://github.com/login/device + current user code"
if [[ -f "$ROOT/portable/GH_DEVICE_LOGIN.md" ]]; then
  echo "  $(grep -E '^\\| User code|^\\| Status|^\\| Verification' "$ROOT/portable/GH_DEVICE_LOGIN.md" | tr '\n' ' ')"
fi
echo "App install (Cursor): GitHub → Settings → Applications → Cursor → add ALL owner repos Read+write"
echo "  Multi-agent oneshot (Batch 224): $ROOT/scripts/owner_grant_ai_agent_access.sh  # Cursor+Codex+Claude+Grok PAT; 8 repos incl. sandbox"
echo "  Docs: $ROOT/docs/MULTI_AGENT_ACCESS.md  |  Inventory: $ROOT/portable/AI_AGENT_ACCESS_INVENTORY.json"
echo "  On App UIs: select ALL repositories including sandbox"
echo "  (until then install_has_main=false; sandbox 404; device user token still can Path C — ignore install_has_main)"
echo "Relaunch / scope: $ROOT/portable/RELAUNCH_WITH_MAIN_SCOPE.md  # (a) App (b) device (c) MAIN_PUSH_TOKEN (d) RELAUNCH — mid-flight cannot gain main"
echo "Status guard (Batch 86/263; fail on OPEN→closed/promoted): $ROOT/scripts/guard_no_status_promotion.py <hardening-checkout>"
echo "  baseline: portable/BATCH70_RESEARCH_STACK_AUDIT.json or portable/STATUS_GUARD_SNAPSHOT.json"
echo "  Batch 263: NO_PACKET vs shape-stripped HAS_PACKET → exit 2 (usage), not false promotions"
echo "  Batch 264: Path B dry-run ALREADY_ALIGNED ⇒ land_needed=false; owner_land_path_b --dry-run idles (no re-run-to-land lie)"
echo "  Batch 265: Batch 262 live-ignore Intent CI-isolates Actions GITHUB_TOKEN (token_source≠env:GITHUB_TOKEN flake)"
echo "  Batch 266: path_c_dry_run IDLE ⇒ write_required_to_land=false; living stack prose 0008–0019 (not stale 0017)"
echo "  Batch 267: when_writable dual-daemon status race → daemon.lock flock + --once sidecar (no leftover --dry-run loop)"
echo "  Batch 324: print_owner Path C line follows PATH_C_LANDED_TIP_DRIFT → refresh_path_c_bundle (pre-324 fell through to APPLY_READY land lie; Batch 261 IDLE-only leftover)"
echo " Batch 327: VERIFY refresh_batch after keep-prior WORKDIR force; pack+CRITICAL include post_batch322_wake_comments.py"
echo "  Batch 329: republish CRITICAL includes print_owner_unblock.sh (Batch 324 tip-drift Path C line was pack-only; living release could stay APPLY_READY-stale with tip_stale=0)"
echo "  Batch 328: inventory refresh INV_BATCH derives from print_owner header (was frozen 323)"
echo "  Batch 329: living tip_refresh assert (Batch 289 CI red after non-tip refresh_batch); MULTI_AGENT_WAKE_BATCH329"
echo " Batch 330: no_token tip-refresh preserves durable 8/8 (DURABLE_SANDBOX_WRITE=n/a)"
echo " Batch 331: grant --check skips inventory refresh when durable_token_source=none"
echo " Batch 332: tip-sync 077464e→388a22c after main #97 inventable (keep-prior; NOT promoted)"
echo " Batch 333: republish release-view retry on rate-limit; STATUS_GUARD tip @388a22c"
echo " Batch 334: grant skip inventory refresh only when durable_token_source=none (not writable=0)"
echo " Batch 335: tip-sync 388a22c→eeebb28 after main #99/#100 (keep-prior; NOT promoted)"
echo " Batch 336: wake poster INTENT tip derives from BASE_TIP (was frozen @077464e); preserve durable inventory on writable=0 DENIED; inventory REFRESH_BATCH_TAG fallback; soften 335 live tip pins; MULTI_AGENT_WAKE"
echo " Batch 337: tip stable @eeebb28 tip_match=1; MULTI_AGENT wake assign; research stack audit open (lemma_closed=false); idle_no_commit"
echo " Batch 337: tip-sync eeebb28→848aea2 after main #101/#107/#102 (keep-prior; NOT promoted; supersedes idle pulse)"
echo " Batch 338: post-Path-C align watch idle @848aea2 tip_match=1; lemma_closed=false"
echo " Batch 338: wake poster skip gate keys off living BASE_TIP (was frozen Batch 329 wake → eng PRs stuck @077464e)"
echo " Batch 340: MULTI_AGENT wake+assign stopped agents @848aea2; Path C IDLE@0019; lemma_closed=false"
echo " Batch 339: living script_stale republish after tip-stable watch @848aea2"
echo " Batch 340: republish CRITICAL includes audit_main_alignment; audit rate-limit/raw fallback; inventory ultimate batch fallback unfrozen (was frozen 336); MULTI_AGENT wake+assign"
echo " Batch 340: audit_main_alignment 403 rate-limit backoff + raw/ls-remote fallback; CI soft-continue transport exit 2"
echo " Batch 341: soften Batch 340 tip-sync Intent live BASE_TIP pin (f244312); living tgz republish after tip-sync"
echo " Batch 341: wake _living_batch_n from print_owner (was frozen _WAKE_BATCH=340); STATUS_GUARD tip→f244312"
echo " Batch 341: grant inventory tip refresh @f244312 (BATCH341_GRANT; preserve_durable)"
echo " Batch 340: inventory ultimate fallback return \"340\" (was frozen 336); REFRESH default 340"
echo " Batch 340: wake poster loads durable MAIN_PUSH_TOKEN files (MAIN first + grant/when_writable drops; App ghs Issues:write)"
echo " Batch 340: tip-sync 848aea2→f244312 after main #108 inventable tip-observe (keep-prior; NOT promoted)"
echo " Batch 340: audit_main_alignment 403 rate-limit backoff; grant inventory tip refresh batch 340 (preserve durable 8/8)"
echo " Batch 341: research stack audit WITHOUT promotion @f244312 (open_premises=13; inventable drafts skipped; eng-only #36/#21/#12 noted; lemma_closed=false)"
echo " Batch 342: WAKE340 tip pins refreshed 848aea2→living f244312 (wake_tip_at_assign preserved)"
echo " Batch 342: inventory tip refresh batch 342 + soften wake-token Intent live tip pin"
echo " Batch 343: living script_stale republish after tip-stable watch @f244312 (print_owner drift after 341/342)"
echo " Batch 343: tip-sync f244312→fcad723 after main #109 (keep-prior; NOT promoted)"
echo " Batch 328: inventory refresh INV_BATCH derives from print_owner header (was frozen 323)"
echo "  Batch 323: grant --check refreshes AI_AGENT_ACCESS_INVENTORY via refresh_ai_agent_access_inventory.py (pre-323 pointer drifted; sandbox.tip vs details); pack+CRITICAL include helper"
echo "  Batch 321: soften Batch 317 live BASE_TIP/VERIFY/PATH_C tip Intent pins to _living_tip; refresh AI_AGENT_ACCESS_INVENTORY tip_sha from durable 8/8"
echo "  Batch 317: tip-sync 0adeb65→077464e after main #89 tip-observe mid-cycle; refresh keep-prior; living tip_stale republish; REFRESH default 317"
echo "  Batch 305: tip-sync 02cfbfd→0adeb65 after main #85 inventable mid-cycle; refresh keep-prior; living tip_stale republish; REFRESH default 305"
echo "  Batch 297: tip-sync 3a29f52→02cfbfd after main #84 tip-observe mid-cycle; refresh keep-prior; living tip_stale republish; REFRESH default 297"
echo "  Batch 289: tip-sync 7d13a88→3a29f52 after main #83 nav inventable mid-cycle; refresh keep-prior; living tip_stale republish; REFRESH default 289"
echo "  Batch 288: republish CRITICAL includes when_writable_land.py (287 fixed lander list-gate but CRITICAL could not detect when_writable-only drift; living release also still lacked 287 probe/refresh → script_stale=1); REFRESH default 288"
echo "  Batch 287: probe_main_write / when_writable require isinstance(repositories, list) (Batch 286 fixed grant only; null/non-list still collapsed via or [] → false empty install_has_main); REFRESH default 287"
echo "  Batch 286: grant --check requires isinstance(repositories, list) (null/non-list ≠ empty install); republish script_stale compares critical script sha256 vs living pack (post-285 tip_match left release without grant fix); Intent REFRESH_BATCH_TAG uses >= not allowlist"
echo "  Batch 285: grant --check treats user-token 403 JSON on /installation/repositories as unavailable (pre-285 empty listing → false install_missing_from_deps=all8 while 8/8 WRITABLE)"
echo "  Batch 283: republish tip_stale when living release BASE_TIP lags local (byte-growth-only missed tip-sync 3b3860d→7d13a88; release lacked grant)"
echo "  Batch 282: pack_portable includes owner_grant_ai_agent_access.sh + AI_AGENT_ACCESS_INVENTORY.json (OWNER_ONE_LINERS referenced grant 8× but tarball omitted it post-281)"
echo "  Batch 281: grant --check durable ls-remote uses token (pre-281 bare https → private sandbox ls_remote=not_found_or_denied while write=WRITABLE)"
echo "  Batch 280: probe_main_write_vectors W2 contents PUT creates throwaway ref first (pre-280 PUT-only → false DENIED 404 Branch not found while W1 WRITABLE)"
echo "  Batch 279: republish stages canonical trial-portable-main-fixes.tgz basename + post-upload size/sha verify (pre-279 --out foo.tgz left living pack stale while printing uploaded OK)"
echo "  Batch 278: pack_portable -h/--help not OUT; refresh APPLY soft-update <<'PY' (Batch 273 leftover); tip-sync bfb7c38→3b3860d"
echo "  Batch 277: owner oneshot/open_pr VERIFY.release-first (Batch 276 leftover preferred dirty living pin → wrong PR release URL)"
echo "  Batch 276: republish living-tag post-pack (pre-pack stale pin → wrong upload target); write_path_c_status VERIFY.release-first"
echo "  Batch 275: refresh MANIFEST.verified_batch release-align from VERIFY.batch (Batch 269 leftover stamped BATCH_TAG); refresh_batch=automation; default tag 275"
echo "  Batch 273: refresh keep-prior APPLY living-tip soft-update + VERIFY pytest preserve (Batch 272 left 542e6ec==(BASE_TIP) lie + focused 0)"
echo "  Batch 272: land-workflows-dry-run Path C idle must match on path-c-dry-run.out alone (union grep only saw Path B ALREADY_ALIGNED)"
echo "  Batch 271: probe_main_write_vectors W3a–W3e dry_run ⇒ DISPATCH_OK_DRY_RUN false_positive; path_b_keys=W1/W2/W4* only (Batch 141 W3f-only leftover)"
echo "  Batch 270: when_writable --once pid-liveness when flock misses live lockfile pid= (sidecar; no shared-status clobber)"
echo "  Batch 269: refresh_path_c_bundle VERIFY.batch aligned to release (was stale 250 vs batch241); refresh_batch automation stamp; no 0020"
echo "  Batch 268: pack_portable living-tag validate-before-write + tip refresh fa32d11→8e359e5 (no 0020; no dirty pin on mismatch)"
echo "  CI job: research-stack-status-guard (continue-on-error; artifact STATUS_GUARD_SNAPSHOT)"
echo "Env write intent: .cursor/environment.json repositoryDependencies → main; relaunch Cloud Agent AFTER merge"
echo "  snapshot: portable/ALIGNED_DRIFT_SNAPSHOT.json  |  release: batch241-path-c-bundle"
echo "Path C ONE-SHOT (owner laptop): gh release download batch241-path-c-bundle -R d6g8k5htny-coder/trial -p 'trial-portable-main-fixes.tgz' -p 'path-c-on-hardening.bundle'"
echo "  then: tar -xzf trial-portable-main-fixes.tgz -C /tmp/path-c-land && /tmp/path-c-land/scripts/owner_path_c_oneshot.sh --from-bundle"
echo "Timer: re-arm permanent-autonomous-align-watch @ 10800s + gh-dylan-device-auth-check @ 1800s (preferred_auth_interval_s=1800; single; no dup)."
echo "PR #41 renewed default tip (ALIGNED). Current default tip may be newer — keep Path B ready if ALIGNED reverts (#32 history)."
echo "Path A OR Path B OK when MISALIGNED. Prefer Path B (Option-B README+AGENTS)."
echo "One-command: $ROOT/scripts/restore_main_face.sh  # short-circuits when already ALIGNED"
echo "Path C BASE_TIP file: $BASE_TIP_LINE"
echo "Path C owner git am (no agent write token): $ROOT/portable/path-c-applied-bundle/APPLY.md"
echo "  patch: $ROOT/portable/path-c-applied-bundle/path-c-on-hardening.patch"
echo "  git bundle (Batch 169 preferred): $ROOT/portable/path-c-applied-bundle/path-c-on-hardening.bundle"
echo "    git fetch …/path-c-on-hardening.bundle cursor/portable-engineering-patches && git merge --ff-only FETCH_HEAD"
# Batch 282: focused count from VERIFY.json (pre-282 hardcoded 90/0 while living tip recount is 92).
VERIFY_FOCUSED="?"
VERIFY_JSON="$ROOT/portable/path-c-applied-bundle/VERIFY.json"
if [[ -f "$VERIFY_JSON" ]]; then
  VERIFY_FOCUSED="$(
    python3 -c '
import json, sys
d = json.load(open(sys.argv[1], encoding="utf-8"))
p = d.get("pytest") or {}
fp = p.get("focused_passed")
rw = p.get("focused_resource_warnings")
fp_s = "?" if fp is None else str(fp)
rw_s = "?" if rw is None else str(rw)
print(f"{fp_s}/{rw_s}")
' "$VERIFY_JSON" 2>/dev/null || echo '?/?'
  )"
fi
echo "  verify: $ROOT/portable/path-c-applied-bundle/VERIFY.json  # problems=0 lemma_closed=false focused ${VERIFY_FOCUSED}"
# Batch 261: do not hardcode APPLY_READY when PATH_C_STATUS already idle.
# Batch 324: PATH_C_LANDED_TIP_DRIFT is also not APPLY_READY — Path C already
# landed; operators need tip-refresh (refresh_path_c_bundle), not land. Pre-324
# only matched IDLE_PATH_C_DONE and fell through to APPLY_READY on tip drift.
if [[ "${IDLE_STATUS}" == "IDLE_PATH_C_DONE" ]]; then
  echo "Path C: $ROOT/scripts/owner_land_path_c.sh --dry-run  # already-on-tip idle (IDLE_PATH_C_DONE) @ ${BASE_TIP_SHORT}; path_c_dry_run → idle not APPLY_READY"
elif [[ "${IDLE_STATUS}" == "PATH_C_LANDED_TIP_DRIFT" ]]; then
  echo "Path C: $ROOT/scripts/refresh_path_c_bundle.sh  # tip-drift (PATH_C_LANDED_TIP_DRIFT) BASE_TIP ${BASE_TIP_SHORT} != live tip ${STATUS_TIP}; refresh keep-prior — not APPLY_READY land"
elif [[ "${IDLE_STATUS}" == "PATH_C_LANDED" ]]; then
  echo "Path C: $ROOT/scripts/owner_land_path_c.sh --dry-run  # path_c_landed (PATH_C_LANDED) @ ${BASE_TIP_SHORT}; not APPLY_READY"
else
  echo "Path C: $ROOT/scripts/owner_land_path_c.sh --dry-run  # APPLY_READY on hardening BASE_TIP ${BASE_TIP_SHORT} (or idle when landed)"
fi
echo "Path C Actions: $ROOT/.github/workflows/land-path-c-on-main.yml  # dry_run default true; MAIN_PUSH_TOKEN for land"
echo "  gh workflow run land-path-c-on-main --repo d6g8k5htny-coder/trial -f dry_run=true"
echo "  gh workflow run land-path-c-on-main --repo d6g8k5htny-coder/trial -f dry_run=false"
echo "CI (no token): land-workflows-dry-run job — validate_land_workflows.py + actionlint + owner --help/--dry-run"
echo "  $ROOT/scripts/validate_land_workflows.py  # dry_run default true; MAIN_PUSH_TOKEN not required"
echo "Path C stays on chatgpt/drive-github-hardening-20260919 (has PACKET.json; rebase onto main CONFLICTS)."
echo "Rebase conflict paths: portable/PATH_C_REBASE_CONFLICT_REPORT_67.json (ci.yml, research.yml, bridge README)."
echo "Rebase helper: $ROOT/scripts/path_c_rebase_helper.sh --dry-run  # prefer abort; never invent research status"
echo "Resolution notes: portable/PATH_C_REBASE_RESOLUTION_NOTES_68.json"
echo "Post-#41: do NOT PATH_C_BASE=main (ALIGNED landing lacks PACKET.json)."
echo "Write live: ${WRITE_STATE} (from PATH_C_STATUS; probe below may confirm). Research audit stays OPEN; lemma_closed=false; no status flips."
echo "pack_portable.sh auto-globs RESTORE_PLAN_* + BATCH*_TOKEN_SEARCH + PATH_C_REBASE_* + BATCH*_RESEARCH_STACK_AUDIT + STATUS_GUARD_SNAPSHOT + ALIGNED_DRIFT_SNAPSHOT + validate_land_workflows (Batch 64+/67+/68+/70+/72+/73+/74+/86)."
echo "Research-stack OPEN audit (Batch 70/132; read-only; no flips): $ROOT/scripts/audit_research_stack_open.py <checkout>"
echo "  artifact: portable/BATCH132_RESEARCH_STACK_AUDIT.json  |  docs/MECHANICAL_FINDINGS_MAIN.md"
echo "Scientific effect: NONE"
echo

echo "=== OWNER_ONE_LINERS (paths) ==="
echo "  $ROOT/portable/OWNER_ONE_LINERS.md"
echo "  $ROOT/portable/LAND.md"
echo "  $ROOT/docs/OWNER_ACTIONS_MAIN.md"
echo "  $ROOT/.github/workflows/land-option-b-on-main.yml"
echo "  $ROOT/.github/workflows/land-path-c-on-main.yml"
echo "  $ROOT/scripts/restore_main_face.sh"
echo

if [[ -f "$ROOT/portable/OWNER_ONE_LINERS.md" ]]; then
  echo "=== OWNER_ONE_LINERS (file) ==="
  cat "$ROOT/portable/OWNER_ONE_LINERS.md"
  echo
fi

echo "=== live probe / audit (durable file-token discovery; never prints secrets) ==="
echo "# Batch 262: probe_main_write(+vectors) load env OR well-known file tokens"
echo "#   (MAIN_PUSH_TOKEN / .secrets / /tmp/gh-dylan-auth/access_token) so live"
echo "#   section matches PATH_C_STATUS WRITABLE; PATH_C_IGNORE_FILE_TOKENS=1 skips files."
echo "# write probe single-ref (0=writable, 1=denied, 2=transport):"
python3 "$ROOT/scripts/probe_main_write.py" || true
echo
echo "# multi-vector Path B probe (0=any Path-B-capable writable):"
python3 "$ROOT/scripts/probe_main_write_vectors.py" || true
echo
echo "# alignment audit (0=ALIGNED, 1=MISALIGNED, 2=transport):"
set +e
python3 "$ROOT/scripts/audit_main_alignment.py"
audit_ec=$?
set -e
echo "(audit exit=$audit_ec)"
echo
echo "# watch one-liner:"
python3 "$ROOT/scripts/watch_main_alignment.py" || true
echo
echo "# wait until ALIGNED (poll watch; default 30s / max 2h; --verify runs VERIFY_AFTER_MERGE):"
echo "$ROOT/scripts/wait_until_aligned.sh"
echo "$ROOT/scripts/wait_until_aligned.sh --verify"
echo
echo "=== owner land scripts (run with *owner* gh auth / write on main) ==="
echo "# Path B — PREFERRED one-command restore:"
echo "$ROOT/scripts/restore_main_face.sh --dry-run"
echo "$ROOT/scripts/restore_main_face.sh"
echo "# Path B — underlying owner script:"
echo "$ROOT/scripts/owner_land_path_b.sh --dry-run"
echo "$ROOT/scripts/owner_land_path_b.sh"
echo "$ROOT/scripts/owner_land_path_b.sh --after-merge"
echo "$ROOT/scripts/path_b_dry_run.py"
echo "$ROOT/scripts/path_c_dry_run.py"
echo "$ROOT/scripts/refresh_restore_plan.py --batch 65"
echo "$ROOT/scripts/check_autonomous_window.py"
echo "$ROOT/scripts/watch_main_alignment.py  # embeds autonomous_window + route (Batch 62+)"
echo "$ROOT/scripts/aligned_drift_watch.py  # exit 0/1/2; --restore-if-writable"
echo "$ROOT/scripts/when_writable_land.py --once --dry-run"
echo "$ROOT/scripts/when_writable_land.py  # background; tmux when-writable-land"
echo "# Path C — Batch 165 ONE-SHOT (token→open PR / land; else unblock menu):"
echo "$ROOT/scripts/owner_path_c_oneshot.sh --dry-run"
echo "$ROOT/scripts/owner_path_c_oneshot.sh"
echo "$ROOT/scripts/owner_path_c_oneshot.sh --from-bundle"
echo "# Path C — engineering: apply_all 0001–0004 + 0008–0019 on hardening tip:"
echo "$ROOT/scripts/owner_land_path_c.sh --dry-run"
echo "$ROOT/scripts/owner_land_path_c.sh --from-bundle  # ONE-SHOT from release tarball"
echo "$ROOT/scripts/owner_land_path_c.sh"
echo "# Path C — owner PR from path-c-applied-bundle (Batch 151; branch cursor/path-c-portable-fixes):"
echo "$ROOT/scripts/owner_open_path_c_pr.sh --dry-run"
echo "$ROOT/scripts/owner_open_path_c_pr.sh  # git am bundle → push → PR into hardening"
echo "# Path A — HOLD VOID; default PATH_A_MODE=revert32 (or ready_merge for a fresh OPEN port PR):"
echo "$ROOT/scripts/owner_land_path_a.sh"
echo
echo "=== copy-paste Path C (needs write on main) ==="
echo "# Batch 165 ONE-SHOT (preferred entry):"
echo "$ROOT/scripts/owner_path_c_oneshot.sh --dry-run"
echo "$ROOT/scripts/owner_path_c_oneshot.sh"
echo "# dry-run first (no write); then land on hardening BASE_TIP — avoid PATH_C_REBASE_ONTO_MAIN post-#41:"
echo "$ROOT/scripts/owner_land_path_c.sh --dry-run"
echo "$ROOT/scripts/owner_land_path_c.sh --from-bundle"
echo "$ROOT/scripts/owner_land_path_c.sh"
echo "# Batch 151 owner PR (bundle am → cursor/path-c-portable-fixes → PR hardening):"
echo "$ROOT/scripts/owner_open_path_c_pr.sh --dry-run"
echo "$ROOT/scripts/owner_open_path_c_pr.sh"
echo "# or Actions (trial secret MAIN_PUSH_TOKEN):"
echo "# 1) Settings → Secrets → Actions → MAIN_PUSH_TOKEN (Contents:Write on main)"
echo "#    ONE-SHOT: $ROOT/scripts/owner_set_main_push_token.sh --dry-run"
echo "#             MAIN_PUSH_TOKEN=… $ROOT/scripts/owner_set_main_push_token.sh --dispatch"
echo "#             # or: $ROOT/scripts/owner_set_main_push_token.sh --from-gh --dispatch"
echo "# 2) Actions → land-path-c-on-main → Run workflow → dry_run=false"
echo "gh workflow run land-path-c-on-main --repo d6g8k5htny-coder/trial -f dry_run=true"
echo "gh workflow run land-path-c-on-main --repo d6g8k5htny-coder/trial -f dry_run=false"
echo "# or: $ROOT/portable/patches/apply_all.sh on a writable hardening tip checkout"
echo
echo "=== copy-paste Path B (optional) ==="
echo "# 1) Settings → Secrets → Actions → MAIN_PUSH_TOKEN (Contents:Write on main)"
echo "# 2) Actions → land-option-b-on-main → Run workflow → dry_run=false"
echo "gh workflow run land-option-b-on-main --repo d6g8k5htny-coder/trial -f dry_run=false"
echo
echo "Scientific effect: NONE"
